steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'hackgt/$REPO_NAME:$COMMIT_SHA', '-t', 'hackgt/$REPO_NAME:latest', '.']
  timeout: 120s
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=hackgt --password=$$DOCKER_PASSWORD']
  secretEnv: ['DOCKER_PASSWORD']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'hackgt/$REPO_NAME:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'hackgt/$REPO_NAME:latest']
- name: 'hackgt/builder-trigger-beehive-build'
  secretEnv: ['TRAVIS_TOKEN']
- name: 'hackgt/builder-pr-autodeploy'
  secretEnv: ['GH_TOKEN']
  env:
    - 'REPO_NAME=$REPO_NAME'
    - 'BRANCH_NAME=$BRANCH_NAME'
timeout: 180s
secrets:
- kmsKeyName: projects/hackgt-cluster/locations/global/keyRings/hackgt-build/cryptoKeys/hackgt-build-key
  secretEnv:
    DOCKER_PASSWORD: CiQATk4Dt7S6ki9JbJvw22WkKHsdyQhEOflZeK/1IJz/rJ18LmASNQD6KHO+IyjkNS/GHaDxJuLmbFXCr1kU5xzVVHaePe1CZeI1P1J/vyO3y1lXvSJpyID0hoXm
    TRAVIS_TOKEN: CiQATk4Dt3x0+R2zKUvt090ul3dDhcZUnYsGoQfOzSjKquHVwiUSPwD6KHO+mVuFK9L8KYnFzg20D24Ih3FPujmuEiNPugBU0qTlTSQFcEMQrv93l8sLPlW8E8k0cg3v0mZqI721Rg==
    GH_TOKEN: CiQATk4Dt+aCWrSvmOjyeFMx1cE6IdyMcp/9QICxGVymKcwNRnUSUQD6KHO+AF+uv67L1thZYzN4WY9U/UYDy69RR8KUEKNwfiUW2vxtvLOjMawfj4NHEnIthVC6Z9aWqb3In6l+/+mcKh5ZgVFKrWY8Whh+LEZGGA==
